{block content}

<ol>
	<li class="current">Formulář</li>
	<li>Výsledky</li>
</ol>

<h2>1. Vyplň formulář</h2>
<p>Promiň, tu růžovou jsem si nemohl odpustit.</p>
{$form->render('begin')}
{$form->render('errors')}
<fieldset>
	<legend>Přihlášení na Fakturoid</legend>
	<table>
		<tr id="username">
			<th>{$form['username']->label}</th>
			<td>{$form['username']->control}<small>.fakturoid.cz</small></td>
		</tr>
		<tr id="apiKey">
			<th>{$form['apiKey']->label}</th>
			<td>{$form['apiKey']->control} <small>(Nastavení &rarr; Heslo a API &rarr; API token)</small></td>
		</tr>
	</table>
</fieldset>
<fieldset>
	<legend>Nějaké to nastavení navíc</legend>
	<table>
		<tr>
			<th>{$form['year']->label}</th>
			<td>{$form['year']->control}</td>
		</tr>
		<tr>
			<th>{$form['expenses']->label}</th>
			<td>{$form['expenses']->control} <a href="http://www.jakpodnikat.cz/pausalni-vydaje-procentem.php">?</a></td>
		</tr>
		<tr>
			<th>{$form['student']->label}</th>
			<td>{$form['student']->control} <a href="http://www.jakpodnikat.cz/sleva-na-dani-studenta.php">?</a></td>
		</tr>
	</table>
</fieldset>
{$form['ok']->control}
{$form->render('end')}
