{block content}

<h1>FakturoidCalc</h1>
<p>
	Jsem malinký robot, který si povídá s <a href="http://www.fakturoid.cz">Fakturoidem</a> a pokouší se spočítat,
	kolik asi zaplatíš na daních státu. Sestavil mě <a href="http://twitter.com/littlemaple">Honza Javorek</a>.
	Prý neposkytuje žádné záruky a vyhrazuje si právo být omylný. Neukládám nic z toho co mnou
	proteče. Pokud tomu nevěříš, koukni se na <a href="https://github.com/Littlemaple/FakturoidCalc">mě přes rentgen</a>.
</p>

{control mainForm}

{ifset $results}
	<p>Je libo výsledky?</p>
{/if}