<!DOCTYPE html>
<html lang="cs" dir="ltr">
<head>
	<meta charset="utf-8">

	<meta name="author" content="Jan Javorek (honza@javorek.net)">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>FakturoidCalc</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="shortcut icon" type="image/x-icon" href="http://www.fakturoid.cz/favicon.ico">
</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	{include #content}
</body>
</html>
